apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-project-pv-volume
  namespace: database
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/persistent-volumes/laravel-project-database"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-project-pv-claim
  namespace: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi