apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: spinnaker
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/volumes/minio-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "zabbix-4"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
  namespace: spinnaker
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi