---
  - hosts: loadbalancer
    become: true
    tasks: 
      - name: install nginx
        yum: name=nginx state=present update_cache=yes

      - name: ensure nginx service started
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes
      
      - name: stop and disable firewall service
        ansible.builtin.service:
          name: firewalld
          state: stopped
          enabled: no

      - name: configure nginx site
        template: src=./template/nginx.conf.j2 dest=/etc/nginx/conf.d/demo.conf mode=755
        notify: restart nginx

    handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted  